name: Docker Image CI/CD

on:
  push:
    branches:
      - main

env:
  AZURE_REGISTRY_NAME: viimaneregistry
  AZURE_REGISTRY_USERNAME: ${{ secrets.AZURE_REGISTRY_USERNAME }}
  AZURE_REGISTRY_PASSWORD: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.AZURE_REGISTRY_NAME }}
          username: ${{ env.AZURE_REGISTRY_USERNAME }}
          password: ${{ env.AZURE_REGISTRY_PASSWORD }}
      
      - name: Pull Directus Docker image
        run: docker pull directus/directus:latest
      
      - name: Tag Docker image for Azure Registry
        run: docker tag directus/directus:latest ${{ env.AZURE_REGISTRY_NAME }}/directus:latest
      
      - name: Push Docker image to Azure Registry
        run: docker push ${{ env.AZURE_REGISTRY_NAME }}/directus:latest
