name: Docker Image CI/CD

on:
  push:
    branches:
      - main

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}
      
      - name: Pull Directus Docker image
        run: docker pull directus/directus
      
      - name: Tag Docker image
        run: docker tag directus/directus raigorobin/viimanekatse:latest
      
      - name: Expose port 80
        run: docker run -d -p 80:80 raigorobin/viimanekatse:latest
      
      - name: Push Docker image
        run: docker push raigorobin/viimanekatse:latest
